# Generated by Django 5.0.3 on 2024-03-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_photo_car_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInvetory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cars_count', models.IntegerField()),
                ('cars_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
