# Generated by Django 5.0.3 on 2024-03-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carinvetory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarInvetory',
            new_name='CarInventory',
        ),
    ]
